# Generated by Django 2.2 on 2019-11-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('description_elements', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Tytuł')),
                ('in_volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tom (np. "t. 2")')),
                ('editors_abbrev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skrót redakcji/opracowania itp. (np. red.)')),
                ('published_year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rok wydania')),
                ('annotation', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Uwagi')),
                ('sorting_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nazwa sortująca (pole automatyczne)')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Opis bibliograficzny (pole automatyczne)')),
                ('authors', models.ManyToManyField(blank=True, related_name='chapters_as_author', to='description_elements.Author', verbose_name='Autorstwo')),
                ('cat_lvl_3', models.ManyToManyField(related_name='chapters', to='categories.CategoryLevelThree', verbose_name='Kategorie i podkategorie')),
                ('editors', models.ManyToManyField(blank=True, related_name='encompassing_bib_units_as_editor', to='description_elements.Author', verbose_name='Redakcja/Opracowanie')),
                ('encompassing_bibliographic_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependent_bibliographic_units', to='description_elements.EncompassingBibliographicUnit', verbose_name='Opublikowane w: (wydawnictwo zwarte)')),
                ('keywords', models.ManyToManyField(blank=True, related_name='chapters', to='description_elements.Keyword', verbose_name='Wyrażenia kluczowe')),
                ('published_locations', models.ManyToManyField(blank=True, related_name='encompassing_bib_units', to='description_elements.Location', verbose_name='Miejsce/miejsca wydania')),
            ],
            options={
                'verbose_name': '2. Rozdział/artykuł/hasło w wydawnictwie zwartym',
                'verbose_name_plural': '2. Rozdziały/artykuły/hasła w wydawnictwach zwartych',
                'ordering': ['sorting_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Tytuł')),
                ('editors_abbrev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skrót redakcji/opracowania itp. (np. red.)')),
                ('translators_abbrev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skrót tłumaczenia (np. tłum.)')),
                ('published_year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rok wydania')),
                ('volumes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tomy (np. "t. 1-2")')),
                ('annotation', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Uwagi')),
                ('sorting_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nazwa sortująca (pole automatyczne)')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Opis bibliograficzny (pole automatyczne)')),
                ('authors', models.ManyToManyField(blank=True, related_name='books_as_author', to='description_elements.Author', verbose_name='Autorstwo')),
                ('cat_lvl_3', models.ManyToManyField(related_name='books', to='categories.CategoryLevelThree', verbose_name='Kategorie i podkategorie')),
                ('editors', models.ManyToManyField(blank=True, related_name='books_as_editor', to='description_elements.Author', verbose_name='Redakcja/Opracowanie itp.')),
                ('keywords', models.ManyToManyField(blank=True, related_name='books', to='description_elements.Keyword', verbose_name='Wyrażenia kluczowe')),
                ('published_locations', models.ManyToManyField(blank=True, related_name='books', to='description_elements.Location', verbose_name='Miejsce/miejsca wydania')),
                ('translators', models.ManyToManyField(blank=True, related_name='books_as_translator', to='description_elements.Translator', verbose_name='Tłumaczenie')),
            ],
            options={
                'verbose_name': '1. Wydawnictwo zwarte',
                'verbose_name_plural': '1. Wydawnictwa zwarte',
                'ordering': ['sorting_name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Tytuł')),
                ('annotation', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Uwagi')),
                ('sorting_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nazwa sortująca (wypełniana automatycznie)')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Opis bibliograficzny (pole automatyczne)')),
                ('published_year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rok wydania periodyku (pole automatyczne)')),
                ('authors', models.ManyToManyField(blank=True, related_name='articles_as_author', to='description_elements.Author', verbose_name='Autorstwo')),
                ('cat_lvl_3', models.ManyToManyField(related_name='articles', to='categories.CategoryLevelThree', verbose_name='Kategorie i podkategorie')),
                ('keywords', models.ManyToManyField(blank=True, related_name='articles', to='description_elements.Keyword', verbose_name='Wyrażenia kluczowe')),
                ('periodical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contained_articles', to='description_elements.Periodical', verbose_name='Opublikowane w: (periodyk)')),
            ],
            options={
                'verbose_name': '3. Artykuł w periodyku',
                'verbose_name_plural': '3. Artykuły w periodykach',
                'ordering': ['sorting_name'],
            },
        ),
    ]
