# Generated by Django 2.2 on 2019-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodical',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tytuł periodyku'),
        ),
        migrations.AlterField(
            model_name='periodical',
            name='vol_info_lvl_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numeracja wolumenu poziom 1'),
        ),
        migrations.AlterField(
            model_name='periodical',
            name='vol_info_lvl_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numeracja wolumenu poziom 2'),
        ),
        migrations.AlterField(
            model_name='periodical',
            name='vol_info_lvl_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numeracja wolumenu poziom 3'),
        ),
    ]
