# Generated by Django 2.2 on 2019-11-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevelOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kategoria poz. 1 (max. 80 znaków)')),
            ],
            options={
                'verbose_name': 'Kategoria poz. 1',
                'verbose_name_plural': 'Kategorie poz. 1',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryLevelTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='---', max_length=255, verbose_name='Kategoria poz. 2 (max. 80 znaków)')),
                ('formatted_name', models.CharField(default='---', max_length=255, verbose_name='Kategoria poz. 2 pełna nazwa')),
                ('cat_lvl_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories2', to='categories.CategoryLevelOne', verbose_name='Kategoria poz. 1')),
            ],
            options={
                'verbose_name': 'Kategoria poz. 2',
                'verbose_name_plural': 'Kategorie poz. 2',
                'ordering': ['cat_lvl_1', 'name'],
                'unique_together': {('cat_lvl_1', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CategoryLevelThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='---', max_length=255, verbose_name='Kategoria poz. 3 (max. 95 znaków)')),
                ('formatted_name', models.CharField(default='---', max_length=255, verbose_name='Kategoria poz. 3 pełna nazwa')),
                ('cat_lvl_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories3', to='categories.CategoryLevelTwo', verbose_name='Kategoria poz. 2')),
            ],
            options={
                'verbose_name': 'Kategoria poz. 3',
                'verbose_name_plural': 'Kategorie poz. 3',
                'ordering': ['cat_lvl_2', 'name'],
                'unique_together': {('cat_lvl_2', 'name')},
            },
        ),
    ]
