# Generated by Django 2.2 on 2019-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevelone',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kategoria poz. 1 (max. 50 znaków)'),
        ),
        migrations.AlterField(
            model_name='categorylevelthree',
            name='name',
            field=models.CharField(default='---', max_length=105, verbose_name='Kategoria poz. 3 (max. 105 znaków)'),
        ),
        migrations.AlterField(
            model_name='categoryleveltwo',
            name='name',
            field=models.CharField(default='---', max_length=100, verbose_name='Kategoria poz. 2 (max. 100 znaków)'),
        ),
    ]
