# Generated by Django 2.2 on 2019-12-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20191202_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylevelone',
            name='sorting_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa sortująca (pole automatyczne)'),
        ),
        migrations.AddField(
            model_name='categorylevelthree',
            name='sorting_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa sortująca (pole automatyczne)'),
        ),
        migrations.AddField(
            model_name='categoryleveltwo',
            name='sorting_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa sortująca (pole automatyczne)'),
        ),
    ]
