# Generated by Django 2.2 on 2019-12-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20191214_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevelone',
            name='sorting_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa sortująca (pole automatyczne)'),
        ),
        migrations.AlterField(
            model_name='categorylevelthree',
            name='sorting_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa sortująca (pole automatyczne)'),
        ),
        migrations.AlterField(
            model_name='categoryleveltwo',
            name='sorting_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa sortująca (pole automatyczne)'),
        ),
    ]
